echo "include rose-pine-moon.conf" >> ~/.config/kitty/kitty.conf

font_family IosevkaTerm Nerd Font Mono
font_size 10.0
# padding order: top right bottom left (pts)
window_padding_width 5 0 0 5

# Rose Pine – more transparent background
background_opacity 0.75

# Optional: keep dimming behavior normal
dim_opacity 1.0
