/* ===== Rose Pine Moon Rofi ===== */

* {
    font: "JetBrainsMono Nerd Font 12.5";
    background: #232136F2;
    foreground: #e0def4;

    bg: #232136F2;
    bg-alt: #2a273fF2;
    surface: #393552F2;

    accent: #c4a7e7;
    highlight: #eb6f92;

    radius: 12px;
}

window {
    width: 42%;
    border: 2px solid @accent;
    border-radius: @radius;
    padding: 20px;
    background: @bg;
}

mainbox {
    spacing: 16px;
}

inputbar {
    background: @surface;
    padding: 12px 16px;
    border-radius: @radius;
    text-color: @foreground;
}

prompt {
    text-color: @accent;
}

entry {
    text-color: @foreground;
}

listview {
    spacing: 10px;
    fixed-height: 0;
}

element {
    padding: 10px 12px;
    border-radius: @radius;
    background: transparent;
}

element alternate {
    background: @bg-alt;
}

element selected {
    background: @highlight33;
    foreground: @bg;
}

element-text {
    highlight: @highlight;
    text-color: @foreground;
}

element-icon {
    size: 26px;
}