# ~/.config/fuzzel/fuzzel.ini

[main]
font=JetBrainsMono Nerd Font:size=13
prompt="  "
icons-enabled=true
icon-theme=Papirus
anchor=center
lines=10
width=40
horizontal-margin=20
vertical-margin=20

border-radius=12
border-width=2
background-color=232136cc

[colors]
background=232136dd
text=e0def4ff
prompt=e0def4ff
input=e0def4ff
selection=393552ff
selection-text=e0def4ff
border=c4a7e7ff